[project]
name = "learn-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax[cuda12]>=0.4.35",
    "jupyter>=1.1.1",
]
